---

#Setup
- name: Post upgrade check XR
  connection: network_cli
  

#Ask for user and password
  # vars_prompt:
  #   - name: "ansible_user"
  #     prompt: "Enter router username"
  #     private: no
  #   - name: "ansible_password"
  #     prompt: "Enter router password"
  #     private: yes

#Set Vars
  vars:
 #Where to store the postcheck file
    precheck_path: "/data/Cisco/"
 #Set user and password
    ansible_connection: network_cli
    # ansible_user: "{{ ansible_user }}"
    # ansible_password: "{{ ansible_password }}"

#Run Tasks
  tasks:
 #Gather facts
  - name: Gather facts from Cisco XR router
    ios_facts:
      gather_subset: min
    register: router_facts

 #Get pre-install check shows
  - name: show hw-module
    cisco.iosxr.iosxr_command:
      commands: 
      - show hw-module fpd
    register: show_hw_module

  - name: show ipv4
    cisco.iosxr.iosxr_command:
      commands: 
      - show ipv4 interface summary
    register: show_ipv4

  - name: show mpls
    cisco.iosxr.iosxr_command:
      commands: 
      - show mpls ldp neighbor
    register: show_mpls

  - name: show bgp
    cisco.iosxr.iosxr_command:
      commands: 
      - show bgp ipv4 all summary
    register: show_bgp

  - name: show route
    cisco.iosxr.iosxr_command:
      commands:
      - show route
    register: show_route

  - name: show interface
    cisco.iosxr.iosxr_command:
      commands:
      - show interface
    register: show_interface

  - name: Erase existing file
    file:
      path: "{{ precheck_path }}{{ ansible_net_hostname }}-postcheck.txt"
      state: absent

  - name: Write debug message to a file
    lineinfile:
      path: "{{ precheck_path }}{{ ansible_net_hostname }}-postcheck.txt"
      line: |
        #### show hw-module fpd ####
        {{ show_hw_module.stdout[0].strip().strip("show") }}

        ##### show ipv4 interface summary ####
        {{ show_ipv4.stdout[0].strip().strip("show") }}

        ##### show mpls ldp neighbor ####
        {{ show_mpls.stdout[0].strip().strip("show") }}

        ##### show bgp ipv4 all summary ####
        {{ show_bgp.stdout[0].strip().strip("show") }}

        ##### show route ####
        {{ show_route.stdout[0].strip().strip("show") }}

        ##### show interface ####
        {{ show_interface.stdout[0].strip().strip("show") }}
      state: present
      create: yes

 #open precheck and postcheck files and compare

  - name: Display the diff of two files
    command: 'diff "{{ precheck_path }}{{ ansible_net_hostname }}-precheck.txt" "{{ precheck_path }}{{ ansible_net_hostname }}-postcheck.txt"'
    register: diff_result
    failed_when: false

  - name: Display fancy diff
    debug:
      msg: |
        {% for line in diff_result.stdout_lines %}
        {{ line.replace('<', 'Removed: ').replace('>', '  Added: ') }}
        {% endfor %}
        {{ "-"*90 }}
      verbosity: 0

#  - name: Display default diff
#    debug:
#      msg: |
#        {% for line in diff_result.stdout_lines %}
#        {{ line }}
#        {% endfor %}
#        {{ "-"*90 }}
#      verbosity: 0

 #commit changes
  - name: Prompt user for committing changes and store the result
    pause:
      prompt: "Do you want to commit changes? (y/n)"
    register: input

  - name: Store input
    set_fact:
      commit_changes: "{{ input.user_input }}"
    when: input.user_input is defined

  - name: Run the IOS command
    cisco.iosxr.iosxr_command:
      commands:
        - install commit
    when: commit_changes == 'y'

  - name: DO NOT Commit the IOS
    debug:
      msg: "input was 'n' the upgrade must have broke stuff"           
      verbosity: 0
    when: commit_changes == 'n'

  - name: Unrecognized input   
    debug:
      msg: "options were (y/n) what is this {{ commit_changes  }} ???"
      verbosity: 0
    when: commit_changes not in ['y', 'n']

  - name: Exit the router
    cisco.iosxr.iosxr_command:
      commands:
        - exit