---
    
- name: Get Device Facts
  hosts: mx
  connection: local
  gather_facts: no
  
- name: install requirements;
  shell: |
    ansible-galaxy collection install junipernetworks.junos -p /usr/share/ansible/collections
    cd /usr/share/ansible/collections
    ls

  roles:
    - Juniper.junos

  #Set Vars
  vars:
    ansible_connection: network_cli
    #ansible_network_os: junipernetworks.junos.junos
    ansible_network_os: junos
    ansible_user: "{{ ansible_user }}"
    # baud: 9100
    # cs_passwd: hello_pwd
    # cs_user: hello_usr
    # level: yes
    # port: "69"
    # baud: "9100"
    ansible_password: "{{ ansible_password }}"

  tasks:
    - name: Retrieve facts from device running Junos OS
      juniper_junos_facts:
        savedir: "{{ playbook_dir }}"
    - name: Print version
      debug:
        var: junos.version