---

- hosts: localhost
  gather_facts: no
  vars:
    nios_provider:
      host: infoblox.itb.lab
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      wapi_version: '2.11'

  connection: local
  tasks:
    - name: run shell commands
      shell: |
        pip3 install infoblox-client
        ansible-galaxy collection install infoblox.nios_modules -p /usr/share/ansible/collections/ansible_collections
        ansible-galaxy collection install community.general -p /usr/share/ansible/collections/ansible_collections

    - name: fetch host
      set_fact:
        host: "{{ lookup('infoblox.nios_modules.nios_lookup', 'search', filter={'fqdn~': 'cir-'}, provider=nios_provider) }}"

    - name: output
      debug:
        msg: "{{ host }}"

    - name: extract ipv4 addresses from host
      set_fact:
        ipv4_addresses: "{{ host | json_query('ipv4addrs[*].ipv4addr') }}"


    - name: debug specific variable (ipv4 address)
      debug:
        msg: "{{ host.ipv4addrs.ipv4addr if host.ipv4addrs is defined else '' }}"

