---

- hosts: localhost
  gather_facts: no
  vars:
    nios_provider:
      host: infoblox.itb.lab
      username: admin
      password: infoblox
      wapi_version: '2.11'

  connection: local
  tasks:
    # - name: fetch all networkview objects
    #   set_fact:
    #     networkviews: "{{ lookup('nios', 'networkview', provider=nios_provider) }}"

    - name: run shell commands
      shell: |
        pip3 install infoblox-client
        # python --version
        # ansible --version
        # pip3 show infoblox-client
        ansible-galaxy collection install infoblox.nios_modules -p /usr/share/ansible/collections/ansible_collections
        # ansible-galaxy collection list infoblox.nios_modules
        ansible-galaxy collection install community.general -p /usr/share/ansible/collections/ansible_collections
        # ansible-galaxy collection list community.general

    - name: run show commands
      shell: |       
        cd /usr/share/ansible/collections/ansible_collections
        ls
        cd /usr/share/ansible/collections/ansible_collections/infoblox/nios_modules
        ls

    # - name: run show runner commands
    #   shell: |       
    #     cd /runner/requirements_collections/ansible_collections
    #     ls
    # - name: Install collection
    #   command: ansible-galaxy collection list infoblox.nios_modules

    # - name: List installed collections
    #   command: ansible-galaxy collection list

    - name: fetch host
      set_fact:
        host: "{{ lookup('infoblox.nios_modules.nios_lookup', 'search', filter={'fqdn~': 'cir-'}, provider=nios_provider) }}"

    - name: output
      debug:
        msg: "{{ host }}"

    - name: extract ipv4 addresses from host
      set_fact:
        ipv4_addresses: "{{ host | json_query('ipv4addrs[*].ipv4addr') }}"


    - name: debug specific variable (ipv4 address)
      debug:
        msg: "{{ host.ipv4addrs.ipv4addr if host.ipv4addrs is defined else '' }}"

